services:
    _defaults:
        autowire: true
        autoconfigure: true

    Dealroadshow\K8S\Framework\Core\Pod\PodSpecProcessor: ~
    Dealroadshow\K8S\Framework\Core\Pod\PodTemplateSpecProcessor: ~
    Dealroadshow\K8S\Framework\Core\Job\JobSpecProcessor: ~
    Dealroadshow\K8S\Framework\Dumper\AppDumper: ~
    Dealroadshow\K8S\Framework\Renderer\YamlRenderer: ~
    Dealroadshow\K8S\Framework\Helper\Metadata\MetadataHelper: ~
    Dealroadshow\K8S\Framework\Helper\Names\DefaultNamesHelper: ~
    Dealroadshow\K8S\Framework\App\AppProcessor: ~
    Dealroadshow\K8S\Framework\ResourceMaker\ConfigMapMaker: ~
    Dealroadshow\K8S\Framework\ResourceMaker\DeploymentMaker: ~
    Dealroadshow\K8S\Framework\ResourceMaker\SecretMaker: ~
    Dealroadshow\K8S\Framework\ResourceMaker\JobMaker: ~
    Dealroadshow\K8S\Framework\ResourceMaker\CronJobMaker: ~

    Dealroadshow\K8S\Framework\Helper\Metadata\MetadataHelperInterface: '@Dealroadshow\K8S\Framework\Helper\Metadata\MetadataHelper'
    Dealroadshow\K8S\Framework\Helper\Names\NamesHelperInterface: '@Dealroadshow\K8S\Framework\Helper\Names\DefaultNamesHelper'
    Dealroadshow\K8S\Framework\Dumper\Context\ContextInterface: '@Dealroadshow\K8S\Framework\Dumper\Context\Context'

    Dealroadshow\Bundle\K8SBundle\:
        resource: '../../../src/'
        exclude:
          - '../../../src/DependencyInjection'
          - '../../../src/Resources'

    Dealroadshow\Bundle\K8SBundle\CodeGeneration\TemplateRenderer:
        arguments:
          - '%dealroadshow_k8s.class_templates_dir%'

    Dealroadshow\Bundle\K8SBundle\CodeGeneration\ClassDetailsResolver\ManifestResolver:
        arguments:
          - '%dealroadshow_k8s.namespace_prefix%'

    Dealroadshow\K8S\Framework\Dumper\Context\Context:
        arguments:
            $includeTags: '%dealroadshow_k8s.filter.tags.include%'
            $excludeTags: '%dealroadshow_k8s.filter.tags.exclude%'

    Dealroadshow\Bundle\K8SBundle\CodeGeneration\ClassDetailsResolver\AppResolver:
      arguments:
        - '%dealroadshow_k8s.code_dir%'
        - '%dealroadshow_k8s.namespace_prefix%'

    Dealroadshow\K8S\Framework\Core\ManifestProcessor:
        arguments:
          - !tagged_iterator { tag: 'dealroadshow_k8s.resource_maker' }

    Dealroadshow\K8S\Framework\Core\Container\ContainerMaker:
        arguments:
          - !tagged_iterator { tag: 'dealroadshow_k8s.container_image_middleware', default_priority_method: 'priority' }

    Dealroadshow\K8S\Framework\Registry\AppRegistry:
        arguments:
          - !tagged_iterator { tag: 'dealroadshow_k8s.app' }

    Dealroadshow\K8S\Framework\Registry\ManifestRegistry:
        arguments:
          - !tagged_iterator { tag: 'dealroadshow_k8s.manifest' }

    Dealroadshow\Bundle\K8SBundle\CodeGeneration\ManifestGenerator\ContextRegistry:
        arguments:
          - !tagged_iterator { tag: 'dealroadshow_k8s.manifest_generator.context' }

    Dealroadshow\Bundle\K8SBundle\Command\GenerateManifestCommand:
        tags:
          - { name: 'console.command', command: 'k8s:generate:manifest' }
          - { name: 'console.command', command: 'k8s:gen:manifest' }
          - { name: 'console.command', command: 'k8s:gen:man' }

    Dealroadshow\Bundle\K8SBundle\Command\GenerateAppCommand:
        tags:
          - { name: 'console.command', command: 'k8s:generate:app' }
          - { name: 'console.command', command: 'k8s:gen:app' }

    Dealroadshow\Bundle\K8SBundle\Command\DumpAppCommand:
        tags:
          - { name: 'console.command', command: 'k8s:dump:app' }

    Dealroadshow\Bundle\K8SBundle\Command\DumpAllCommand:
        arguments:
            $manifestsDir: '%dealroadshow_k8s.manifests_dir%'
        tags:
          - { name: 'console.command', command: 'k8s:dump:all' }
