parameters:
    dealroadshow_k8s.annotation_domain: 'dealroadshow.com'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $env: '%kernel.environment%'
            $annotationDomain: '%dealroadshow_k8s.annotation_domain%'
            $manifestsDir: '%dealroadshow_k8s.manifests_dir%'

    Dealroadshow\K8S\Framework\App\AppProcessor: ~
    Dealroadshow\K8S\Framework\Core\Pod\PodSpecProcessor: ~
    Dealroadshow\K8S\Framework\Core\Pod\PodTemplateSpecProcessor: ~
    Dealroadshow\K8S\Framework\Core\Job\JobSpecProcessor: ~
    Dealroadshow\K8S\Framework\Dumper\AppDumper: ~
    Dealroadshow\K8S\Framework\Renderer\YamlRenderer: ~
    Dealroadshow\K8S\Framework\Renderer\JsonRenderer: ~
    Dealroadshow\K8S\Framework\Helper\Metadata\MetadataHelper: ~
    Dealroadshow\K8S\Framework\Helper\Names\DefaultNamesHelper: ~
    Dealroadshow\K8S\Framework\ResourceMaker\ConfigMapMaker: ~
    Dealroadshow\K8S\Framework\ResourceMaker\DeploymentMaker: ~
    Dealroadshow\K8S\Framework\ResourceMaker\SecretMaker: ~
    Dealroadshow\K8S\Framework\ResourceMaker\JobMaker: ~
    Dealroadshow\K8S\Framework\ResourceMaker\CronJobMaker: ~
    Dealroadshow\K8S\Framework\ResourceMaker\IngressMaker: ~
    Dealroadshow\K8S\Framework\ResourceMaker\ServiceMaker: ~
    Dealroadshow\K8S\Framework\ResourceMaker\PersistentVolumeClaimMaker: ~
    Dealroadshow\K8S\Framework\ResourceMaker\StatefulSetMaker: ~
    Dealroadshow\K8S\Framework\ResourceMaker\PriorityClassMaker: ~
    Dealroadshow\K8S\Framework\ResourceMaker\ServiceAccountMaker: ~
    Dealroadshow\K8S\Framework\ResourceMaker\HorizontalPodAutoscalerMaker: ~
    Dealroadshow\K8S\Framework\ResourceMaker\Prometheus\PodMonitorMaker: ~
    Dealroadshow\K8S\Framework\ResourceMaker\Prometheus\ServiceMonitorMaker: ~
    Dealroadshow\K8S\Framework\ResourceMaker\Prometheus\PrometheusRuleMaker: ~
    Dealroadshow\K8S\Framework\Registry\AppRegistry: ~
    Dealroadshow\K8S\Framework\Registry\ManifestRegistry:
        public: true
    Dealroadshow\K8S\Framework\Util\ManifestAppFinder: ~
    Dealroadshow\Bundle\K8SBundle\EventListener\AfterMethodSubscriber: ~
    Dealroadshow\Bundle\K8SBundle\EventListener\BeforeMethodSubscriber: ~
    Dealroadshow\Bundle\K8SBundle\EventListener\ReplicasMethodSubscriber: ~
    Dealroadshow\Bundle\K8SBundle\EventListener\ResourcesMethodSubscriber: ~
    Dealroadshow\Bundle\K8SBundle\EventListener\AutoSetReplicasSubscriber: ~
    Dealroadshow\Bundle\K8SBundle\EventListener\AutoSetResourcesSubscriber: ~
    Dealroadshow\K8S\Framework\Renderer\FilteringService: ~
    Dealroadshow\K8S\Framework\Util\ManifestReferencesService: ~
    Dealroadshow\K8S\Framework\Util\VersionedManifestReferencesService: ~
    Dealroadshow\K8S\Framework\Proxy\EventDispatcherBridgeInterceptor: ~
    Dealroadshow\K8S\Framework\ManifestGenerator\ManifestsGenerationService: ~

    Dealroadshow\K8S\Framework\Helper\Metadata\MetadataHelperInterface: '@Dealroadshow\K8S\Framework\Helper\Metadata\MetadataHelper'
    Dealroadshow\K8S\Framework\Helper\Names\NamesHelperInterface: '@Dealroadshow\K8S\Framework\Helper\Names\DefaultNamesHelper'
    Dealroadshow\K8S\Framework\Dumper\Context\ContextInterface: '@Dealroadshow\K8S\Framework\Dumper\Context\Context'
    Dealroadshow\K8S\Framework\Core\Container\ContainerMakerInterface: '@Dealroadshow\K8S\Framework\Core\Container\ContainerMaker'

    Dealroadshow\Bundle\K8SBundle\:
        resource: '../../../src/'
        exclude:
          - '../../../src/DependencyInjection'
          - '../../../src/Resources'

    Dealroadshow\Bundle\K8SBundle\CodeGeneration\TemplateRenderer:
        arguments:
          - '%dealroadshow_k8s.class_templates_dir%'

    Dealroadshow\Bundle\K8SBundle\CodeGeneration\ClassDetailsResolver\ManifestResolver:
        arguments:
          - '%dealroadshow_k8s.namespace_prefix%'

    Dealroadshow\K8S\Framework\Dumper\Context\Context:
        arguments:
            $includeTags: '%dealroadshow_k8s.filter.tags.include%'
            $excludeTags: '%dealroadshow_k8s.filter.tags.exclude%'

    Dealroadshow\Bundle\K8SBundle\CodeGeneration\ClassDetailsResolver\AppResolver:
      arguments:
        - '%dealroadshow_k8s.code_dir%'
        - '%dealroadshow_k8s.namespace_prefix%'

    Dealroadshow\K8S\Framework\Core\ManifestProcessor:
        arguments:
          $makers: !tagged_iterator { tag: 'dealroadshow_k8s.resource_maker' }

    Dealroadshow\K8S\Framework\Core\Container\ContainerMaker:
        arguments:
            $middlewares: !tagged_iterator { tag: 'dealroadshow_k8s.middleware.container_image', default_priority_method: 'priority' }

    Dealroadshow\Bundle\K8SBundle\CodeGeneration\ManifestGenerator\ContextRegistry:
        arguments:
          - !tagged_iterator { tag: 'dealroadshow_k8s.manifest_generator.context' }

    Dealroadshow\K8S\Framework\Proxy\ProxyFactory:
        arguments:
            $bodyInterceptors: !tagged_iterator { tag: 'dealroadshow_proximity.interceptor.body' }
            $resultInterceptors: !tagged_iterator { tag: 'dealroadshow_proximity.interceptor.result' }

    Dealroadshow\Bundle\K8SBundle\Checksum\ChecksumsService:
        arguments:
            $calculators: !tagged_iterator { tag: 'dealroadshow_k8s.checksum_calculator' }

    Dealroadshow\K8S\Framework\Renderer\RendererInterface: '@Dealroadshow\K8S\Framework\Renderer\YamlRenderer'
