site_name: Dealroadshow K8S Framework
docs_dir: src
site_dir: dist
theme:
  name: material
  logo: assets/finsight-logo-white.svg
  favicon: assets/finsight-logo-black.svg
extra_css:
  - //cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.3/styles/atom-one-light.min.css
extra_javascript:
  - //cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js
  - assets/init.js
markdown_extensions:
  - admonition
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: php
          class: php
nav:
  - Overview: index.md
  - How to read this docs: how-to-read.md
  - Our vision: vision.md
  - Installation: installation.md
  - Getting started: getting-started.md
  - Basic concepts:
      - Manifests: concepts/manifests.md
      - Containers: concepts/containers.md
      - Apps: concepts/apps.md
  - Application lifecycle: lifecycle.md
  - Manifest methods interception: methods-interception.md
  - Environments management: env-management.md
  - Distribute your apps: reusable-apps.md
